### ISSUE TITLE
The InvertibilityError causing by rounding error

### ISSUE THREAD

**Issue by GiggleLiu** [HanLi123/NiLang#3]
## Reversibility check
Due to the fact that floating pointing numbers are not exactly reversible, sometimes the invertibility check might fail due to the rounding error.

To fix this issue, you may want to make the check less restrictive
```julia
NiLangCore.GLOBAL_ATOL[] = 1e-6  # default is 1e-8
```

Or just turn off the check in the program (only if you are sure the program is correct)
```julia
@routine @invcheckoff begin
    ...
end
```
Turning off the check will make your program faster too!

## Gradient check
About the gradient check, it can fail due to either the rounding error or the finite difference error, you may want to check the gradient manually with the `NiLang.AD.ng` function (numeric gradient).
```julia
julia> NiLang.AD.ng(jin, copy.((out,b,ma,jinzhi,spread,bili)), 6; iloss=1, δ=1e-4)
-5449.643843214744

julia> NiLang.AD.ng(jin, copy.((out,b,ma,jinzhi,spread,bili)), 5; iloss=1, δ=1e-4)
4503-element Array{Float64,1}:
 -0.0023380584934784565
 -0.0021096593627589755
 -0.0019811886886600405
  ⋮
 -0.009526640951662557
 -0.006004695478623034
  0.0
```

and 
```julia
julia> NiLang.AD.gradient(Val(1), jin, copy.((out,b,ma,jinzhi,spread,bili)))[end]
-5449.643116967733

julia> NiLang.AD.gradient(Val(1), jin, copy.((out,b,ma,jinzhi,spread,bili)))[end-1]
4503-element Array{Float64,1}:
 -0.0005285958114468947
 -0.00030225263725219137
 -0.00017545437275561654
  ⋮
 -0.010422627668532736
 -0.0069140339974312695
  0.0
```

**Comment by GiggleLiu** [comment]
NiLang's result is consistent with ForwardDiff
```julia
julia> ForwardDiff.gradient(spread) do x
           T = eltype(x)
           jin(T(out), T.(b), T.(ma), T.(jinzhi), x, T(bili))[1]
       end
4503-element Array{Float64,1}:
 -0.0005285958114492949
 -0.0003022526372545943
 -0.00017545437275801756
  ⋮
 -0.010422627668531371
 -0.0069140339974298965
  0.0
```

This confirms that the numeric differentiation is suffering from the finite difference error.

**Comment by HanLi123** [comment]
Thanks very much! After turning off the check, it works perfectly.

**Comment by HanLi123** [comment]
Maybe I could pull request for the method cov and correlation :)  @GiggleLiu

**Comment by GiggleLiu** [comment]
That sounds great!
I think these functions should belong to this file
https://github.com/GiggleLiu/NiLang.jl/blob/master/src/stdlib/statistics.jl

Thanks.
